name: Python CI

on:
  push:
    branches:
      - main  # Run CI for pushes to the main branch
  pull_request:
    branches:
      - main  # Run CI for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version (adjust as needed)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install all the dependencies from requirements.txt

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$(pwd)  # Set the PYTHONPATH to the current directory

    - name: Run tests
      run: |
        pytest tests/ --maxfail=1 --disable-warnings -q  # Run the tests
